language: node_js
node_js:
  - '4.2'
  
env:
  global:
  - secure: b6CqlcdTm81iYjGf/7/o2coKK5pVaQQOmllsuTdLMSwk/YMI+50jNVr9CjPVwIN0XmJoTqUM0oMPPINFV5E6cFfrbsLuhCN7DBwbGwDCKWve166ZZV7XQpKcSYpdRXI2Bkm9nBZ3tZ6NV5Ms7Aj1ywtRtpJ2subACqui9UYVRKjYdvElI8nOelfRkXV4jsqPy1xNmTzqJBdm3aWdSdKykh2+f4V8ojcS/Yqfnhial0vyLeVLry2rRz2r9CdW502QONe19Dgb7vRNxbbcx0pc8d2Zm290auJdeR4ag0Y1FgvfElC+ppZgq5Mj/X3rWSPqclULUUi20CBw+XJ96GOaWhWTyMR+HrVz9DQ4qHqQraF8kzaZUrQ+NI3AK6GuoWdV6LnZW+uVfTj9Sc0GHt3vZcO+8xfN7PAfwFv228y2l+df211lry4lOXumR4SvGXR4UC+d2AIk4BJ7gu/hQ+wKJev9oJewYPNeLlA6khqHoQbvUu8cRyIQMSz0pM7UjIFAuOUnxVxJTGbfRvHgDSMeg10uL9W49OxCn+mbDa6aPM5TzMPEYBRCVUR0pbAWiLWQQk/j7v5wNCvWUS0K6cPiawk+HfisxZ+xSLK80+7mqFHdp2HUW2pt8P7AyXQdYJ1GN9KoYO5k/Z0rN2PKg+u351YMx1Xp81da4Sy81Zl2rAs=
  - secure: JLFo+PTl+tq5dH5riYKxGmLd0OGlggxdaV1iXstDEOcjtX8XGlaMpkmEApamVpQfHkas8BUN8zpio0YGE1bE+VTXjxpvT+xFhOCfEujw9IKLetXtIoOH4PEWoXXFzTEl4q1WdNjTAYRk6fc62LscNg/Ner7RTC3ErkMkRyIkxem/E/E9329Vike1IY5rg6R4NDtLIANP8BaxKtrSGojJ3GHl4zG5aiLRnfEz0DHf5qMwp5SB0TgB05frYOz2i0Qc3StdD7khDvExEX+LGCzbI71VC0Oi3My0LNMWSZXQQu9KcP85eoVgexPb5v7wKAJW4aewSyg1ly68sJ5tyIGcRN9o+AXlghXQ67KFOrF26rdFs16m+G3//w2rq6y7ckt8W1tUkLN3g4dODZsF++OJfdDpM648uyEiDzw0ye/UjANCQiJg+O2Z1HAkguk9bjT9YocguejFTRSxHEMy9lKwQqDI85mMjnuE33veZa6TqH4nNZrpObsCA7uf20rT4ZbSMWbGEpocouPNi9Mqvy/C7B2wlhm0kTCtURGPWH2tqUDFeJOgglqiVn0piPzjPmq3H63VClOe/HeC5jb/DHyCM6qLTm2XPnePpTHHVQqb4c0czLZd+WTOPtTGD57GfpPCPCIfaymBDplcN9fzoGwsacYsFKfhnMfn35DfDAIOWh8=
  - secure: c5JhLkGB1tamsQ3SrIjvDjm925wj4IBEfiLpS32LWJLqpWy1TOA++zKiTp2XsFMq3w7mju2c1j+n/HrJeMp+OhVEJUkiE/LjjZyEdtJplPBIPPC3hSPLWXNVrxk3JZZs66W6fBJQijB9M9GIpMkw99XtFEE8DiSKky+wkN2y3TWyzN3C5NkvZqvwt08eMRF0WqVaf8k0Kj+8csLxXxxFNPkKK2THnB16fAWca3F2BCUlf2g2otI8ixgRRQg8a+7M9h50aENPbisd8TDoDAZex2yRLG5Axv+SoGq/zgilMa2e51sFYqTO0QuU/rBLG8HGJgChCXgjmIPOBxbSsAE6pqvDjG3/iV8oC00/6cFmhAOHp/Bgp5SCmcZ1Lt40/mwNVLpKeXoKQUgwnk8sjAl4qIsce1jAWutvMaSLbBFuNyitmNF7sz9V1COqItaS/4EvOW1cIvq1QKGZPyniUWUrXZmkyf4W3TWQd9gwBClj9hs+aOOZYg0ZCuvNbXwuI/56uAooBB9gtYD637ndFM1BUi8bQ56DFeY+Caoq06uz8GzuvSxQvLAmcA82vfQ3U668eQScZpOCP/zWzkdQIzjzVhyBmxAmtX6v41upWjT5umrnrZvCIWhmKypjJeMZkGgX0O48mCJmz7/9J00h/Av8Q1vhTS4SPKW+L+e3lhkL5+o=

before_deploy:
  - sudo pip install awscli

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    tags: true
